In [1]:
# %pip install https://github.com/pandas-profiling/pandas-profiling/archive/master.zip

In [2]:
import pandas as pd
from pandas_profiling import ProfileReport

C:\Users\Mchomak\AppData\Local\Temp\ipykernel_24848\3034448462.py:2: DeprecationWarning: `import pandas_profiling` is going to be deprecated by April 1st. Please use `import ydata_profiling` instead.
  from pandas_profiling import ProfileReport

### Загрузка данных

In [3]:
df=pd.read_csv("train.csv")

In [4]:
df.head()

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Data columns (total 81 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Id             1460 non-null   int64
 1   MSSubClass     1460 non-null   int64
 2   MSZoning       1460 non-null   object
 3   LotFrontage    1201 non-null   float64
 4   LotArea        1460 non-null   int64
 5   Street         1460 non-null   object
 6   Alley          91 non-null     object
 7   LotShape       1460 non-null   object
 8   LandContour    1460 non-null   object
 9   Utilities      1460 non-null   object
 10  LotConfig      1460 non-null   object
 11  LandSlope      1460 non-null   object
 12  Neighborhood   1460 non-null   object
 13  Condition1     1460 non-null   object
 14  Condition2     1460 non-null   object
 15  BldgType       1460 non-null   object
 16  HouseStyle     1460 non-null   object
 17  OverallQual    1460 non-null   int64
 18  OverallCond    1460 non-null   int64
 19  YearBuilt      1460 non-null   int64
 20  YearRemodAdd   1460 non-null   int64
 21  RoofStyle      1460 non-null   object
 22  RoofMatl       1460 non-null   object
 23  Exterior1st    1460 non-null   object
 24  Exterior2nd    1460 non-null   object
 25  MasVnrType     588 non-null    object
 26  MasVnrArea     1452 non-null   float64
 27  ExterQual      1460 non-null   object
 28  ExterCond      1460 non-null   object
 29  Foundation     1460 non-null   object
 30  BsmtQual       1423 non-null   object
 31  BsmtCond       1423 non-null   object
 32  BsmtExposure   1422 non-null   object
 33  BsmtFinType1   1423 non-null   object
 34  BsmtFinSF1     1460 non-null   int64
 35  BsmtFinType2   1422 non-null   object
 36  BsmtFinSF2     1460 non-null   int64
 37  BsmtUnfSF      1460 non-null   int64
 38  TotalBsmtSF    1460 non-null   int64
 39  Heating        1460 non-null   object
 40  HeatingQC      1460 non-null   object
 41  CentralAir     1460 non-null   object
 42  Electrical     1459 non-null   object
 43  1stFlrSF       1460 non-null   int64
 44  2ndFlrSF       1460 non-null   int64
 45  LowQualFinSF   1460 non-null   int64
 46  GrLivArea      1460 non-null   int64
 47  BsmtFullBath   1460 non-null   int64
 48  BsmtHalfBath   1460 non-null   int64
 49  FullBath       1460 non-null   int64
 50  HalfBath       1460 non-null   int64
 51  BedroomAbvGr   1460 non-null   int64
 52  KitchenAbvGr   1460 non-null   int64
 53  KitchenQual    1460 non-null   object
 54  TotRmsAbvGrd   1460 non-null   int64
 55  Functional     1460 non-null   object
 56  Fireplaces     1460 non-null   int64
 57  FireplaceQu    770 non-null    object
 58  GarageType     1379 non-null   object
 59  GarageYrBlt    1379 non-null   float64
 60  GarageFinish   1379 non-null   object
 61  GarageCars     1460 non-null   int64
 62  GarageArea     1460 non-null   int64
 63  GarageQual     1379 non-null   object
 64  GarageCond     1379 non-null   object
 65  PavedDrive     1460 non-null   object
 66  WoodDeckSF     1460 non-null   int64
 67  OpenPorchSF    1460 non-null   int64
 68  EnclosedPorch  1460 non-null   int64
 69  3SsnPorch      1460 non-null   int64
 70  ScreenPorch    1460 non-null   int64
 71  PoolArea       1460 non-null   int64
 72  PoolQC         7 non-null      object
 73  Fence          281 non-null    object
 74  MiscFeature    54 non-null     object
 75  MiscVal        1460 non-null   int64
 76  MoSold         1460 non-null   int64
 77  YrSold         1460 non-null   int64
 78  SaleType       1460 non-null   object
 79  SaleCondition  1460 non-null   object
 80  SalePrice      1460 non-null   int64
dtypes: float64(3), int64(35), object(43)
memory usage: 924.0+ KB

### Поиск кореляций

In [6]:
# profile = ProfileReport(df, title='Houses Prices')

In [7]:
# profile.to_notebook_iframe()

In [8]:
# profile.to_file(output_file="your_report.html")

### Самые важные параметры влияющие на Итоговую цену дома:

- OverallQual: Общее качество материала и отделки
- YearBuilt: Первоначальная дата постройки
- YearRemodAdd: Дата реконструкции
- TotalBsmtSF: Общая площадь подвала в квадратных футах
- 1stFlrSF: Площадь первого этажа в квадратных футах
- GrLivArea: Жилая площадь выше уровня земли, квадратные футы
- TotRmsAbvGrd: Общее количество номеров выше класса (не включая ванные комнаты)
- GarageYrBlt: Год постройки гаража
- GarageArea: Размер гаража в квадратных футах
- PoolQC: Качество бассейна

In [9]:
def preprocessing(df):
    df['Alley'].fillna('Missing', inplace=True)
    df['MasVnrType'].fillna('Missing', inplace=True)
    df['BsmtQual'].fillna('Missing', inplace=True)
    df['BsmtCond'].fillna('Missing', inplace=True)
    df['BsmtExposure'].fillna('Missing', inplace=True)
    df['BsmtFinType1'].fillna('Missing', inplace=True)
    df['BsmtFinType2'].fillna('Missing', inplace=True)
    df['Electrical'].fillna('Missing', inplace=True)
    df['FireplaceQu'].fillna('Missing', inplace=True)
    df['GarageType'].fillna('Missing', inplace=True)
    df['GarageFinish'].fillna('Missing', inplace=True)
    df['GarageQual'].fillna('Missing', inplace=True)
    df['GarageCond'].fillna('Missing', inplace=True)
    df['PoolQC'].fillna('Missing', inplace=True)
    df['Fence'].fillna('Missing', inplace=True)
    df['MiscFeature'].fillna('Missing', inplace=True)
    df['LotFrontage'].fillna('Missing', inplace=True)    

    # если не указан тип шпона, то ставим 0, а если указан, то ставим среднее значение
    # df['MasVnrArea'].fillna(lambda x: 0 if x["MasVnrType"]=="Missing" else df['MasVnrArea'].mean(), inplace=True)
    # df['GarageYrBlt'].fillna(lambda x: 0 if x["GarageType"]=="Missing" else df['GarageYrBlt'].mean(), inplace=True)
    # df['GarageCars'].fillna(lambda x: 0 if x["GarageType"]=="Missing" else df['GarageCars'].mean(), inplace=True)
    # df['GarageArea'].fillna(lambda x: 0 if x["GarageType"]=="Missing" else df['GarageArea'].mean(), inplace=True)

    df['MasVnrArea'].fillna(df['MasVnrArea'].mean(), inplace=True)
    df['GarageYrBlt'].fillna(df['GarageYrBlt'].mean(), inplace=True)
    df['GarageCars'].fillna(df['GarageCars'].mean(), inplace=True)
    df['GarageArea'].fillna(df['GarageArea'].mean(), inplace=True)

    zeros=[
        "MiscVal",
        "PoolArea",
        "ScreenPorch",
        "3SsnPorch",
        "EnclosedPorch",
        "OpenPorchSF",
        "WoodDeckSF",
        "TotalBsmtSF",
        "LowQualFinSF",
        "BsmtUnfSF",
        "BsmtFinSF2",
        "BsmtFinSF1",
        "MasVnrArea",
    ]
    for name in zeros:
        df.drop(name, axis=1, inplace=True)
    
    columns=[]
    for col in df:
        if df[col].dtypes=="object":
            columns.append(col)

    df=pd.get_dummies(df, columns=columns, drop_first= True)
    return df

In [10]:
abt = df.copy()
abt=preprocessing(abt) 
abt.head()

,Id,MSSubClass,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,1stFlrSF,2ndFlrSF,GrLivArea,...,SaleType_ConLI,SaleType_ConLw,SaleType_New,SaleType_Oth,SaleType_WD,SaleCondition_AdjLand,SaleCondition_Alloca,SaleCondition_Family,SaleCondition_Normal,SaleCondition_Partial
0,1,60,8450,7,5,2003,2003,856,854,1710,...,False,False,False,False,True,False,False,False,True,False
1,2,20,9600,6,8,1976,1976,1262,0,1262,...,False,False,False,False,True,False,False,False,True,False
2,3,60,11250,7,5,2001,2002,920,866,1786,...,False,False,False,False,True,False,False,False,True,False
3,4,70,9550,7,5,1915,1970,961,756,1717,...,False,False,False,False,True,False,False,False,False,False
4,5,60,14260,8,5,2000,2000,1145,1053,2198,...,False,False,False,False,True,False,False,False,True,False

### Modeling

In [11]:
from sklearn.model_selection import train_test_split
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler
from matplotlib import pyplot as plt 
import seaborn as sns

In [12]:
X = abt.drop(['SalePrice', 'Id'], axis=1)
y = abt['SalePrice']

In [13]:
X_train, X_test, y_train, y_test= train_test_split(X, y, test_size=0.3, random_state=123)

In [14]:
X.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1460 entries, 0 to 1459
Columns: 356 entries, MSSubClass to SaleCondition_Partial
dtypes: bool(334), float64(1), int64(21)
memory usage: 727.3 KB

### Setup ML Pipelines

In [15]:
from sklearn.model_selection import GridSearchCV
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier

In [16]:
pipelines = {
    'rf': make_pipeline(StandardScaler(), RandomForestClassifier(random_state=123)),
    # 'gb': make_pipeline(StandardScaler(), GradientBoostingClassifier(random_state=123))
}

In [17]:
GradientBoostingClassifier().get_params()

{'ccp_alpha': 0.0,
 'criterion': 'friedman_mse',
 'init': None,
 'learning_rate': 0.1,
 'loss': 'log_loss',
 'max_depth': 3,
 'max_features': None,
 'max_leaf_nodes': None,
 'min_impurity_decrease': 0.0,
 'min_samples_leaf': 1,
 'min_samples_split': 2,
 'min_weight_fraction_leaf': 0.0,
 'n_estimators': 100,
 'n_iter_no_change': None,
 'random_state': None,
 'subsample': 1.0,
 'tol': 0.0001,
 'validation_fraction': 0.1,
 'verbose': 0,
 'warm_start': False}

In [18]:
grid = {
    'rf': {
        'randomforestclassifier__n_estimators':[100,200,300]
    }
}

In [19]:
from sklearn.metrics import accuracy_score, precision_score, recall_score
import pickle
import numpy as np

In [20]:
def train_model(pipelines):
  fit_models = {}
  for algo, pipeline in pipelines.items():
    print(f'Training the {algo} model.')
    model = GridSearchCV(pipeline, grid[algo], n_jobs=-1, cv=10)
    model.fit(X_train, y_train)
    fit_models[algo] = model 
    with open(f'{algo}.pkl', 'wb') as f: 
      pickle.dump(fit_models[algo], f)

  return fit_models

In [21]:
# fit_models=train_model(pipelines)

In [22]:
# for alg, model in fit_models.items(): 
#   yhat = model.predict(X_test)
#   accuracy = accuracy_score(y_test, yhat)
#   precision = precision_score(y_test, yhat,average='micro')
#   recall = recall_score(y_test, yhat,average='micro')
#   print(f'Metrics for {alg}: accuracy- {accuracy}, recall- {recall}, precision- {precision}')

In [23]:
with open('rf.pkl', 'rb') as f: 
  reloaded_model = pickle.load(f)

In [33]:
buf = pd.read_csv('train.csv')
buf1 = buf.copy()
buf1=preprocessing(buf1)
buf1=buf1.drop('Id', axis=1)

test_df = pd.read_csv('test.csv')
abt_test = test_df.copy()
abt_test=preprocessing(abt_test)
abt_test=abt_test.drop('Id', axis=1)

In [34]:
abt_test.head()

,MSSubClass,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,1stFlrSF,2ndFlrSF,GrLivArea,BsmtFullBath,...,SaleType_ConLI,SaleType_ConLw,SaleType_New,SaleType_Oth,SaleType_WD,SaleCondition_AdjLand,SaleCondition_Alloca,SaleCondition_Family,SaleCondition_Normal,SaleCondition_Partial
0,20,11622,5,6,1961,1961,896,0,896,0.0,...,False,False,False,False,True,False,False,False,True,False
1,20,14267,6,6,1958,1958,1329,0,1329,0.0,...,False,False,False,False,True,False,False,False,True,False
2,60,13830,5,5,1997,1998,928,701,1629,0.0,...,False,False,False,False,True,False,False,False,True,False
3,60,9978,6,6,1998,1998,926,678,1604,0.0,...,False,False,False,False,True,False,False,False,True,False
4,120,5005,8,5,1992,1992,1280,0,1280,0.0,...,False,False,False,False,True,False,False,False,True,False

In [35]:
# for col in buf1:
#     if col not in abt_test:
#         print(col)
#         abt_test[col]=0

In [36]:
buf1.head()

,MSSubClass,LotArea,OverallQual,OverallCond,YearBuilt,YearRemodAdd,1stFlrSF,2ndFlrSF,GrLivArea,BsmtFullBath,...,SaleType_ConLI,SaleType_ConLw,SaleType_New,SaleType_Oth,SaleType_WD,SaleCondition_AdjLand,SaleCondition_Alloca,SaleCondition_Family,SaleCondition_Normal,SaleCondition_Partial
0,60,8450,7,5,2003,2003,856,854,1710,1,...,False,False,False,False,True,False,False,False,True,False
1,20,9600,6,8,1976,1976,1262,0,1262,0,...,False,False,False,False,True,False,False,False,True,False
2,60,11250,7,5,2001,2002,920,866,1786,1,...,False,False,False,False,True,False,False,False,True,False
3,70,9550,7,5,1915,1970,961,756,1717,1,...,False,False,False,False,True,False,False,False,False,False
4,60,14260,8,5,2000,2000,1145,1053,2198,1,...,False,False,False,False,True,False,False,False,True,False

In [29]:
yhat_test = reloaded_model.predict(abt_test)

ValueError: The feature names should match those that were passed during fit.
Feature names unseen at fit time:
- LotFrontage_113.0
- LotFrontage_117.0
- LotFrontage_119.0
- LotFrontage_123.0
- LotFrontage_125.0
- ...

In [ ]:
submission = pd.DataFrame([test_df['Id'], yhat_test]).T
submission.columns = ['Id', 'SalePrice']

In [ ]:
submission.head()

In [ ]:
# index=False, чтобы не писался номер слева таблицы
submission.to_csv('kaggle_submission.csv', index=False)